name: Buildroot_RPi2B_Cast
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Update ke v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev rsync bc wget \
          cpio unzip git perl python3 python3-pip

      - name: Configure for Raspberry Pi 2
        run: make raspberrypi2_defconfig

      - name: Customize Config (GStreamer & Audio)
        run: |
          # Mengaktifkan driver audio & Python
          echo "BR2_PACKAGE_PYTHON3=y" >> .config
          echo "BR2_PACKAGE_ALSA_UTILS=y" >> .config
          echo "BR2_PACKAGE_ALSA_UTILS_APLAY=y" >> .config
          # Mengaktifkan GStreamer untuk Cast Layar
          echo "BR2_PACKAGE_GSTREAMER1=y" >> .config
          echo "BR2_PACKAGE_GST1_PLUGINS_BASE=y" >> .config
          echo "BR2_PACKAGE_GST1_PLUGINS_BASE_ALSA=y" >> .config
          echo "BR2_PACKAGE_GST1_PLUGINS_GOOD=y" >> .config
          echo "BR2_PACKAGE_GST1_PLUGINS_GOOD_RTP=y" >> .config
          echo "BR2_PACKAGE_GST1_PLUGINS_GOOD_UDP=y" >> .config
          echo "BR2_PACKAGE_GST1_PLUGINS_BAD=y" >> .config
          echo "BR2_PACKAGE_GST1_PLUGINS_BAD_FBDEV=y" >> .config
          make olddefconfig

      - name: Build System
        run: make

      - name: Upload SD Card Image
        uses: actions/upload-artifact@v4 # Update ke v4 agar tidak error
        with:
          name: buildroot-rpi2-image
          path: output/images/sdcard.img
